import { NextResponse } from "next/server";
import { getJiraMetrics } from "@/lib/jira";
import { calculateSprintHealth } from "@/lib/insights";

export async function POST() {
  try {
    const metrics = await getJiraMetrics();
    const sprintHealth = calculateSprintHealth(metrics.totalVelocity, metrics.activeBugs);

    // Build the Slack Block Kit payload
    const slackPayload = {
      text: "Daily Standup Summary from VantageMetrics",
      blocks: [
        {
          type: "header",
          text: {
            type: "plain_text",
            text: "📊 Daily Standup Summary",
            emoji: true,
          },
        },
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*Sprint Health*: ${sprintHealth.status} (${sprintHealth.score}/100)\n_${sprintHealth.message}_`,
          },
        },
        {
          type: "divider",
        },
        {
          type: "section",
          fields: [
            {
              type: "mrkdwn",
              text: `*Total Velocity*\n${metrics.totalVelocity} pts`,
            },
            {
              type: "mrkdwn",
              text: `*Active Bugs*\n${metrics.activeBugs}`,
            },
            {
              type: "mrkdwn",
              text: `*To Do*\n${metrics.todo}`,
            },
            {
              type: "mrkdwn",
              text: `*In Progress*\n${metrics.inProgress}`,
            },
            {
              type: "mrkdwn",
              text: `*Done*\n${metrics.done}`,
            },
          ],
        },
        {
          type: "context",
          elements: [
            {
              type: "mrkdwn",
              text: "Generated by VantageMetrics • Action Epic",
            },
          ],
        },
      ],
    };

    const webhookUrl = process.env.SLACK_WEBHOOK_URL;

    if (!webhookUrl) {
      console.log("[Slack Integration] Simulated Push (No SLACK_WEBHOOK_URL found in env):");
      console.dir(slackPayload, { depth: null });
      return NextResponse.json({ success: true, mock: true, message: "Simulated Slack push successful" });
    }

    const response = await fetch(webhookUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(slackPayload),
    });

    if (!response.ok) {
      throw new Error(`Slack API error: ${response.statusText}`);
    }

    return NextResponse.json({ success: true, message: "Pushed to Slack successfully" });
  } catch (error) {
    console.error("[Slack Integration] Error pushing to Slack:", error);
    return NextResponse.json(
      { success: false, error: "Failed to push to Slack" },
      { status: 500 }
    );
  }
}
